---
title: "TOC"
output:
  html_document:
    toc: true
    theme: united

---


## Getting Started {.tabset}

### Exercise 1

- [Get Started Exercise 1](https://github.com/celine-parkk/CHOYOA3/blob/main/choyoa3.qmd)

### Exercise 2

- [Get Started Exercise 2](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/polar-art.R)

### Exercise 3

- [Get Started Exercise 3](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/palette-generators.R)

### Exercise 4 

- [Get Started Exercise 4](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/polar-styled-plots.R)


## Polygon Tricks Task 2 {.tabset} 

### Exercise 1

- [Polygon Tricks (grow.polygon)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/grow-polygon.R)
- [Polygon Tricks (grow-multipolygons)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/grow-multipolygon.R)


### Exercise 2
- [Polygon Tricks (splotch.R)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/splotch.R)
- [Polygon Tricks (smudged_hexagon)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/smudged-hexagon.R)

### Exercse 3
- [Polygon Tricks (perlin-blob.R)](https://github.com/celine-parkk/CHOYOA3/blob/main/perlin-blob.rmd)
- [Polygon Tricks (perlin-heart.R)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/perlin-heart.R)

### Exercise 4
- [Polygon Tricks (perlin-heart-grid.R)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/perlin-heart-grid.R)

### Exercise 5
- [Polygon Tricks (perlin-heart-grid-2.R)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/perlin-heart-grid-2.R)

### Exercise 6
- [Polygon Tricks (perlin-heart-grid-2.R)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/perlin-heart-grid-2.R)

### Exercise 7
- [Polygon Tricks (perlin-heart-animated)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/perlin-heart-animated.R)

### Exercise 8
- [Polygon Tricks (textured-lines)](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/textured-lines.R)



## Pixel Filters Task 3 {.tabset} 

### Exercise 1

- [flametree](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/flametree-example.R)

### Exercise 2

- [ggfx glow](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/ggfx-glow.R)

### Exercise 3

- [ggfx dither](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/ggfx-dither.R)

### Exercise 4

- [ggfx mask](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/ggfx-mask.R)

### Exercise 5

- [ggfx displace](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/ggfx-displace.R)

### Exercise 6

- [ggfx blend](https://github.com/celine-parkk/CHOYOA3/blob/main/exercises/ggfx-blend.R)

## Combining Elementw Task 4 {.tabset}
-
